# Definição da linguagem do projeto que será realizado o build
language: csharp
# versão do SDK que será utilizado para o build
dotnet: 2.2.207
# Informação ser vamos utilizar o monor
mono: none
# Nome da solution que será realizado o build
solution: ImpostoRenda.sln
# instalação de ferramentas que serão utilizadas
install:
  - dotnet tool install --tool-path ./ dotnet-reportgenerator-globaltool 
# Definiçã dos comandos que serão executados   
script:
 - dotnet restore
 - dotnet build
 - dotnet test --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat="opencover" /p:CoverletOutput="/home/travis/build/correia97/ImpostoRenda/results/"
 - ./reportgenerator "-reports:/home/travis/build/correia97/ImpostoRenda/results/coverage.opencover.xml" \
                            "-targetdir:/home/travis/build/correia97/ImpostoRenda/results/" \
                            "-reporttypes:Html" \
                            "-sourcedirs:/home/travis/build/correia97/ImpostoRenda/results/"  