# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
 - job: AzureBuild
   displayName: Build do Azure      
   pool:
      vmImage: 'ubuntu-latest'
   variables:
    buildConfiguration: 'Release'

   steps:
   - task: DotNetCoreCLI@2
     displayName: 'Restore'
     inputs:
      command: 'restore'

   - task: SonarCloudPrepare@1
     displayName: 'Configure Sonar'
     inputs:
       SonarCloud: 'Sonar'
       organization: 'correia97'
       scannerMode: 'MSBuild'
       projectKey: 'correia97_ImpostoRendaLB3'
       projectName: 'ImpostoRendaLB3'
       extraProperties: |
            sonar.exclusions=**/*.js,**/*.css,**/obj/**,**/*.dll,**/*.html,**/*.cshtml
            sonar.branch.name=$(Build.SourceBranchName)
            sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/results/coverage.opencover.xml

   - task: DotNetCoreCLI@2
     displayName: 'Build'
     inputs:
      command: 'build'

   - task: DotNetCoreCLI@2
     displayName: 'Test'
     inputs:
      command: 'test'
      arguments: '--no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"$(Build.SourcesDirectory)/results/\'
      testRunTitle: 'Tests'

   - task: PublishCodeCoverageResults@1
     displayName: 'Cobertura'
     inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/results/coverage.opencover.xml'

   - task: SonarCloudAnalyze@1
     displayName: 'Sonar Analyze'

   - task: SonarCloudPublish@1
     displayName: 'Sonar Publish'
     inputs:
      pollingTimeoutSec: '300'

   - task: CmdLine@2
     displayName: Install CodeCov
     inputs:
      script: 'dotnet tool install --tool-path ./ Codecov.Tool'

   - task: CmdLine@2
     displayName: Publish CodeCov
     inputs:
      script: './codecov -f "$(Build.SourcesDirectory)/results/coverage.opencover.xml" -t $(codecovToken)'

   - task: reportgenerator@4
     displayName: Report
     inputs:
      reports: '$(Build.SourcesDirectory)/results/coverage.opencover.xml'
      targetdir: '$(Build.SourcesDirectory)/results/'
      sourcedirs: '$(Build.SourcesDirectory)/results/'

   - task: PublishTestResults@2
     displayName: Publish Test Result
     inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: '**/*.xml'
      searchFolder: '$(Build.SourcesDirectory)/results/'

   - task: DotNetCoreCLI@2
     displayName: 'Publish API'
     inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/ImpostoRendaLB3.API.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/api'
      workingDirectory: '$(Build.SourcesDirectory)'

   - task: DotNetCoreCLI@2
     displayName: 'Publish WEB'
     inputs:
      command: 'publish'
      publishWebProjects: true
      projects: '**/ImpostoRendaLB3.Web.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/web'
      workingDirectory: '$(Build.SourcesDirectory)'

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifacst'
     inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
     condition: succeededOrFailed()
     
 - job: DockerBuid
   displayName: Build no Docker      
   pool:
      vmImage: 'ubuntu-latest'
   steps:                    
   - task: DockerInstaller@0
     inputs:
      dockerVersion: '17.09.0-ce'
   - task: CmdLine@2
     inputs:
        script: |
          docker build --build-arg sonarLogin=$(sonarToken) --build-arg codecovToken=$(codecovToken) .


 - job: IntegratedTest
   displayName: Docker Build      
   pool:
      vmImage: 'windows-latest'
   steps:                    
    - task: DockerInstaller@0
      inputs:
       dockerVersion: '17.09.0-ce'            
    - task: Npm@1
      inputs:
       command: 'install'
       workingDir: 'install newman -g'   

    - task: CmdLine@2
      inputs:
        script: |
          docker run -d -p 27017:27017 mongo:4.2.0

    - task: CmdLine@2
      inputs:
        script: |
          dotnet run --project src/API/ImpostoRendaLB3.API/ImpostoRendaLB3.API.csproj -c Release
    - task: CmdLine@2
      inputs:
        script: |
          newman run ImpostoRenda.postman_collection.json -n 10 -r cli,json --reporter-json-export ./result/result.json                          