# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  status:
    project:
      default: false
    patch:
      default: false

comment:
  layout: "diff"

flags:
  production:
    paths:
      - src/API/ImpostoRenda.API/
  test:
    paths:
      - Tests/ImpostoRenda.UnitTests/