version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-API
    depends_on:
      - mongo
    ports:
      - 3001:80
  web:
    build: 
      context: .
      dockerfile: Dockerfile-WEB
    depends_on:
      - api
    ports:
      - 3002:80     
  mongo:
    image: mongo:4.1.13
    ports:
       - 27017:27017 

  