version: '3'
services:
  # Api .net Core
  api:
    image: impostoapi
    build:
      context: src/
      dockerfile: DockerfileApi
    depends_on:
      - mongo
    ports:
      - 3001:80
  # MVC .Net Core
  web:
    image: impostoweb
    build: 
      context: src/
      dockerfile: DockerfileWeb
    depends_on:
      - api
    ports:
      - 3002:80 
  #  Imagem Oficial do mongo 
  mongo:
    image: mongo:latest
    ports:
       - 27017:27017 

