version: '3'
services:
  # Api .net Core
  api:
    build: src/API/
    depends_on:
      - mongo
    ports:
      - 3001:80
  # MVC .Net Core
  web:
    build: src/WEB/
    depends_on:
      - api
    ports:
      - 3002:80 
  #  Imagem Oficial do mongo 
  mongo:
    image: mongo:4.1.13
    ports:
       - 27017:27017 
    volumes:
       - vMongo:/data/db
# Volume de dados fora do container       
volumes:
  vMongo:
