version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - Restore
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build          
     - run:
         name: Run Test
         command:
           dotnet test --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutput="./results/"
     - run:
         name: Publish Project
         command: 
          dotnet publish -c Release -o out
      - run:
          name: list
          command: ls  
     - store_artifacts:
          path: Tests/ImpostoRendaLB3.UnitTests/results                  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build 
