version: 2.1
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
     
     - run:
         name: Restore packages
         command:
           dotnet restore
     
     - run:
         name: install Tool CodeCov
         command:
           dotnet tool install --tool-path ./ Codecov.Tool    
     
     - run:
         name: install Tool ReportGenerator
         command:
           dotnet tool install --tool-path ./ dotnet-reportgenerator-globaltool       
     
     - run:
         name: Build App
         command:
           dotnet build
     
     - run:
         name: Run Test
         command:
           dotnet test --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutput=\"./../../results/\"

     - run:
         name: Publish CodeCov
         command:
           ./codecov -f "/root/project/results/coverage.opencover.xml" -t $codeCovToken

     - run:
         name: Generate Report
         command:
           ./reportgenerator "-reports:/root/project/results/coverage.opencover.xml" \
                            "-targetdir:/root/project/results/" \
                            "-reporttypes:Html" \
                            "-sourcedirs:/root/project/results/"  
     
     - store_artifacts:
          path: results/

 dockerBuild:
    machine:
      image: circleci/classic:201808-01 
    steps:
      - checkout

      - run:
          name: docker build
          command: docker build --build-arg sonarLogin=$sonarLogin --build-arg codecovToken=$codeCovToken  -t imp:v1 .

 dockerIntergatedtest:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout      
      - run:
          name: Update Key
          command: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 

      - run:
          name: Update Key 2
          command: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

      - run:
          name: Update Key 3
          command: wget -q -O - https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -

      - run:
          name: Install node
          command: sudo apt-get update && apt-get install -y nodejs npm
      
      - run:
          name: install newman
          command: sudo npm install -g newman

      - run:
          name: docker compose
          command: docker-compose up -d
      
      - run:
          name: Run Tests
          command: newman run ImpostoRenda.postman_collection.json -n 10 -r cli,json --reporter-json-export ./result/result.json   

      - store_artifacts:
          path: results/    

orbs:
  node: 'circleci/node@2.1.1'
  newman: postman/newman@0.0.2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  
      - dockerBuild
      - dockerIntergatedtest