version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run Test
         command:
           dotnet test --no-build
     - run:
         name: Docker Compose
         command:
           docker-compose build
      - run:
         name: Docker images
         command:
           docker images           

            