version: 2.0
jobs:
   build:
     docker: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9
   steps:
     - checkout
     - run:
       name: Restore Packge
       command:
         dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Test App
         command:
           dotnet test --no-build
            