name: Git Buil

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://mcr.microsoft.com/dotnet/core/sdk:2.2
    - name: Restore packge
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build
    - name: Publish
      run: dotnet publish -c Release 
      

