name: Git Buil

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GlobalTool Sona
      run: dotnet tool install --global dotnet-sonarscanner --version 4.7.1
    - name: Restore packge
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
